name: Download

on:
  workflow_dispatch:
    inputs:
      file-url:
        description: 'URL'
        required: true
        default: ''
      file-name:
        description: 'file name'
        required: false
        default: ''

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
    - name: 使用 wget 下载文件
      run: |
        # 从 URL 下载文件，并保存到一个默认的文件名
        wget ${{ github.event.inputs.file-url }} -O downloaded_file
        echo "已下载文件: downloaded_file"

    - name: 解析文件名
      run: |
        # 使用 URL 解析出文件名（从 URL 中提取文件名）
        FILENAME=$(basename ${{ github.event.inputs.file-url }})
        echo "从 URL 中解析出的文件名: $FILENAME"
        # 如果没有提供自定义文件名，使用解析出的文件名
        if [ -z "${{ github.event.inputs.file-name }}" ]; then
          echo "没有提供自定义文件名，使用解析后的文件名。"
          echo "UPLOAD_FILE_NAME=$FILENAME" >> $GITHUB_ENV
        else
          echo "使用自定义文件名: ${{ github.event.inputs.file-name }}"
          echo "UPLOAD_FILE_NAME=${{ github.event.inputs.file-name }}" >> $GITHUB_ENV
        fi

    - name: 设置 ossutil
      uses: yizhoumo/setup-ossutil@v2
      with:
        ossutil-version: '1.7.18'
        endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
        access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

    - name: 上传文件到 OSS
      run: |
        echo "正在上传 $UPLOAD_FILE_NAME 到 OSS..."
        ossutil cp downloaded_file oss://xusharefile/download/$UPLOAD_FILE_NAME
