name: "PKG and publish"

on:
  workflow_dispatch:
    inputs:
      xformers:
        description: 'xformers version'
        required: false
        type: string
        default: ""
      extra_dependencies:
        description: 'extra dependencies'
        required: false
        type: string
        default: ""
      cu:
        description: 'cuda version'
        required: true
        type: string
        default: "124"

      python_minor:
        description: 'python minor version'
        required: true
        type: string
        default: "12"

      python_patch:
        description: 'python patch version'
        required: true
        type: string
        default: "7"
      
      force_no_cache:
        description: 'Force no cache (true/false)'
        required: false
        type: string
        default: 'false'

jobs:
  build_dependencies:
    runs-on: windows-latest
    steps:
      # 设置Python版本
      - uses: actions/setup-python@v5
        with:
          python-version: 3.${{ inputs.python_minor }}.${{ inputs.python_patch }}

      # 打印输入消息
      - name: Print Input Vars
        shell: bash
        run: |
          echo 'Input variable list:'
          echo "force_no_cache:"
          echo ${{ inputs.force_no_cache }}

      # 尝试恢复缓存
      - name: Restore dependencies cache
        id: restore_cache
        uses: actions/cache/restore@v4
        with:
          path: cu${{ inputs.cu }}_python_deps.tar
          key: ${{ runner.os }}-build-cu${{ inputs.cu }}-${{ inputs.python_minor }}
          restore-keys: |
            ${{ runner.os }}-build-cu${{ inputs.cu }}-

      - name: Print restore_cache Result
        shell: bash
        run: |
          echo "steps.restore_cache.outputs.cache-hit:"
          echo ${{ steps.restore_cache.outputs.cache-hit}}

      # 没有缓存则打印个日志
      - name: IF No dependencies
        if: steps.restore_cache.outputs.cache-hit != 'true'
        run: |
          echo "No cache hit, skipping extraction."

      # 如果恢复有文件，则解压恢复的文件
      - name: Have and Extract dependencies
        if: steps.restore_cache.outputs.cache-hit == 'true'
        shell: bash
        run: |
          echo "current path:"
          pwd
          echo 'begin extract deps'
          ls -lah .
          tar -xvf cu${{ inputs.cu }}_python_deps.tar -C .
          echo 'after extract deps'
          ls -lah .
      
      # 如果没有缓存或者强制不使用缓存，则重新执行依赖安装
      - name: Build dependencies
        if: ${{ steps.restore_cache.outputs.cache-hit == 'false' || inputs.force_no_cache == 'true' }}
        shell: bash
        run: |
          echo "steps.restore_cache.outputs.cache-hit:"
          echo ${{ steps.restore_cache.outputs.cache-hit}}
          echo "force_no_cache:"
          echo ${{ inputs.force_no_cache }}

          echo "current path:"
          pwd
          git clone --depth 1 https://github.com/comfyanonymous/ComfyUI.git
          cd ComfyUI
          echo "Newest ComfyUI files:"
          ls -lah .
          python -m pip wheel --no-cache-dir torch torchvision torchaudio ${{ inputs.xformers }} ${{ inputs.extra_dependencies }} --extra-index-url https://download.pytorch.org/whl/cu${{ inputs.cu }} -r requirements.txt pygit2 -w ./temp_wheel_dir
          echo "ComfyUI Deps have installed, the whl files:"
          ls -lah temp_wheel_dir
          mv temp_wheel_dir cu${{ inputs.cu }}_python_deps
          tar cf cu${{ inputs.cu }}_python_deps.tar cu${{ inputs.cu }}_python_deps
          echo "deps tar file info:"
          ls -lh cu${{ inputs.cu }}_python_deps.tar
          mv cu${{ inputs.cu }}_python_deps.tar ../
          cd ..
          echo "current path:"
          pwd
          ls -lah .

      # 如果没有缓存或强制不使用缓存，则保存缓存
      - if: ${{ steps.restore_cache.outputs.cache-hit == 'false' ||  inputs.force_no_cache == 'true' }}
        name: Save dependencies cache
        uses: actions/cache/save@v4
        with:
          path: cu${{ inputs.cu }}_python_deps.tar
          key: ${{ runner.os }}-build-cu${{ inputs.cu }}-${{ inputs.python_minor }}